# Generated by Django 5.1.7 on 2025-03-21 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10)),
                ('is_sell', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=15)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('balance_after', models.DecimalField(decimal_places=0, max_digits=16)),
                ('is_successful', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBankAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=30)),
                ('account_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tài khoản ngân hàng',
                'verbose_name_plural': 'Tài khoản ngân hàng',
                'unique_together': {('user', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='WalletTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('W', 'Rút'), ('D', 'Nạp')], max_length=1)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('balance_after', models.DecimalField(decimal_places=0, max_digits=16)),
                ('status', models.CharField(choices=[('P', 'Đang xử lý'), ('C', 'Hoàn thành'), ('F', 'Bị hủy')], default='P', max_length=1)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('bank_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userLogin.userbankaccounts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'stock_code')},
            },
        ),
    ]
