name: Django Test Project

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Check Python version
        run: python --version
      - name: Check pip version
        run: pip --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
      - name: Install custom packages
        run: |
          pip install git+https://github.com/thinh-vu/vnstock.git@3.1.0.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
      - name: Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate
      - name: Run tests
        run: |
          python manage.py test
      - name: Check code style
        run: |
          pip install flake8
          flake8 . --max-line-length=120 --exclude=venv